### ISSUE TITLE
Extending README file

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#10]
The current version is in a draft state - it should be extended for the proper release.

**Comment by hulpke** [comment]
Is there any functional problem with the README file that would stop the package working -- presumably it would be included with the main GAP distribution as otherwise even the default tests do not run.

**Comment by olexandr-konovalov** [comment]
Actually yes: PackageInfo.g says 
```
README_URL := "http://www.math.colostate.edu/~hulpke/transgrp/README.txt",
```
but the file is called just `README`. The name should be the same, and I would also suggest to rename it to `README.md` and use Markdown - it will be rendered better on GitHub then. 

Otherwise, the short content is not an obstacle for pick up the package and start testing.

**Comment by olexandr-konovalov** [comment]
May we please reopen this - I want to add a proper README. As https://www.gap-system.org/Manuals/pkg/Example-3.5.1/doc/chapA.html#X8383876782480702 says: 

> This should contain "how to get it" (from the GAP ftp- and web-sites) instructions, as well as installation instructions and names of the package authors and their email addresses. The installation instructions should be repeated in the package's documentation, which should be in the doc directory (see A.2). Authors' names and addresses should be repeated both in the package's documentation and in the PackageInfo.g (see below).

Although this guidance is a bit outdated (will be fixed in next release), I will follow parts of it.
