### ISSUE TITLE
Cleaning up the documentation

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#11]
Several things noticed:
- [ ] typos
- [x] `make_doc` script adopted from GRAPE, has hardcoded paths in it
- [x] files in `htm` are autogenerated and there is no need to keep them under version control
- [ ] is that true that no .txt version of documentation is built by that script?
- [ ] wouldn't be better to switch to GAPDoc?

**Comment by fingolfin** [comment]
I partially addressed this in PR #6.

As to GAPDoc: Of course it would be nicer if the manual was written in GAPDoc; but somebody has to do this... pull requests are probably welcome.

**Comment by olexandr-konovalov** [comment]
Especially because part of the XML code could be taken verbatim from the main GAP manual. I can plan to do this next week (for example, I'd rather switch to GAPDoc, than play with gapmacro to get txt files built). And I would see it as a regression of parts of online help that were available in the text forma in GAP 4.8 would disappear in GAP 4.9.

**Comment by olexandr-konovalov** [comment]
@fingolfin not #6 but #16 I guess...

**Comment by hulpke** [comment]
Actually, before anyone starts converting to GAPdoc:

I never have been happy with the XML based GAPdoc format and strongly prefer to use the old documentation format in what are my packages.

Thus I disagree that a switch to GAPdoc would be an improvement.

**Comment by olexandr-konovalov** [comment]
@hulpke I know that you're not a big fan of GAPDoc - that's why I've volunteered to do this myself. With GAPDoc you can, for, example, create manuals with MathJax support, extract examples from manuals for testing etc. You can use AutoDoc package which simplifies writing GAPDoc-based documentation. Also, for a package which is needed to run GAP, I would really like to avoid old manual format which is no longer supported.

**Comment by fingolfin** [comment]
Is there any reason to leave this open? Fixing typos could be done via PR at any time, if you any; the GAPDoc conversion won't happen. And yeah, there are no .txt files, but so what?

**Comment by olexandr-konovalov** [comment]
@hulpke @fingolfin no text files means that users using plain text version of the documentation will not be able to find entries from this package. IMHO, one can not simply ignore this.

**Comment by fingolfin** [comment]
@alex-konovalov No package using gapmacros includes .txt files of the manual -- and I also know nobody who uses a text version of the documentation when they have HTML and PDF.

**Comment by olexandr-konovalov** [comment]
@fingolfin 

> No package using gapmacros includes .txt files of the manual -- 

Ah, that's true - forgot that I myself added tests to exercise that part of GAP library code that converts tex to txt on the fly.

> and I also know nobody who uses a text version of the documentation when they have HTML and PDF.

There are two use cases for that:
- beginners who don't yet learn how to use `SetHelpViewer`
- users of GAP in the terminal via a remote connection
