### ISSUE TITLE
Backporting some changes from GAP

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#17]
One should check and if necessary backport changes made in:
- [x] https://github.com/gap-system/gap/commit/8a7cb56da9ce7b17ed1fe71a8e909429644f3a6c
- [x] https://github.com/gap-system/gap/commit/5ffa0371de2059ecac94538ca047b388496c02bf
- [x] https://github.com/gap-system/gap/commit/bc7f98f5cb2567f5c84cc49dba4eaaf94c2b9d3c (only formatting, one space removed)
- [x] https://github.com/gap-system/gap/commit/3d10dd976c672c77cd281ddde5943a561f1e7cad 
made in the `trans` directory in GAP before this package has been started.

**Comment by hulpke** [comment]
I presume you mean trans, not prim.

3s10dd9 is already in the package

bc7f98f is only formatting.

I've just added 5ffa037 and 8a7cb56

**Comment by olexandr-konovalov** [comment]
Yes, of course trans, thanks - fixed. I've ticked than all boxes above. For cross-references,  5ffa037 and 8a7cb56 from GAP repository were added in https://github.com/hulpke/transgrp/commit/36951db4f337cfcbaca04ccba10780d4c03c3570
