### ISSUE TITLE
Remove TRANSSHAPEFREQS from transgrp again, leave it in library?

### ISSUE THREAD

**Issue by fingolfin** [hulpke/transgrp#18]
I just realized that `TRANSSHAPEFREQS` is not used by `transgrp` at all, it just declares it. The only function actually accessing it is `ShapeFrequencies` in the GAP library. 

Based on that, I am tempted to remove it from this package again, and also in GAP itself, move all references to it into a single file, `lib/galois.gi` (well,and for now its HPC-GAP sibling `hpcgap/lib/galois.gi`. I'd then also remove its declaration from `lib/grpperm.gd` and put that into `galois.gd` or in fact even make it completely local to `galois.gi`.

I guess an alternative approach would be to move `ShapeFrequencies` out of the library into this packages...

@hulpke what do you think? I could implement this quite quickly with PRs for this package and the GAP library, but didn't want to invest work w/o knowing your thoughts on the matter.

**Comment by fingolfin** [comment]
See also https://github.com/gap-system/gap/pull/1733

**Comment by hulpke** [comment]
The function for loading transitive group files also initializes TRANSSHAPEFREQS for new degrees, so that might need adding in galois.gi. Otherwise I'm fine with such a change. If you want to submit a PR I'm happy to merge.
