### ISSUE TITLE
Canonical name of the package: Transgrp or transgrp

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#19]
I suggest to use mixed case: TransGrp. If there are no objections, I will make a PR.

**Comment by hulpke** [comment]
Does this solve any problem but personal preferences on how to call a package?

**Comment by olexandr-konovalov** [comment]
As we know, the naming problem is one of the most difficult problems in computer science :)

It's not known to me whether current lowercase is your personal preference or just the initial name given to the package when it was created.

Of course, for example, LoadPackage is case-insensitive, and  e.g. I do not use uppercase when requesting a package, and I think the same applies to most of users.

The canonical **name** the package is a different other thing. Here authors may combine upper and lower case as they wish. My preferred spelling would be mixed case, like PrimGrp, SmallGrp, TransGrp in this case. This follows the usual way of CamelCase in GAP to name things. Also, it would be good if data libraries will be converted into packages in some consistent way.

I've raised the naming problem in https://github.com/gap-system/gap/issues/792 where you said that you're happy with `TransitiveGroups' - I think that the current abbreviated name is better, so my only suggestion is the spelling.

**Comment by hulpke** [comment]
Now the package exists I see renaming as not worth the cost.

**Comment by olexandr-konovalov** [comment]
Why? There is nothing complicated with this. The repository name stays in lowercase. It's only PackageInfo.g and manual needing the change.

**Comment by olexandr-konovalov** [comment]
I mean, I am perfectly happy with agreeing that we use lowercase for all three packages, and I will rename transgrp. But the argument "it's more trouble because it exists" is not applicable, it's a trivial change.
