### ISSUE TITLE
Backporting some changes from HPC-GAP

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#24]
When we will be preparing this package to work with HPC-GAP, we will need this:
- [x] Move TRANSSHAPEFREQS to galois.{gi,gd}: https://github.com/gap-system/gap/commit/b54c85a826a4a6704e00d8eef2bbc9db8db4146e
- [ ] Merge hpcgap/trans/trans.grp except for atomics: https://github.com/gap-system/gap/commit/2185478e9f62c9281b9043a615686f29aa3bca55 
- [ ] sync hpcgap/trans/trans.gd: https://github.com/gap-system/gap/commit/dbbcb22d207a56ca6b2748af75314c80ee32cacd
- [ ] sync hpcgap/trans/trans.grp: https://github.com/gap-system/gap/commit/eee3bda3816d2bf4b3683194d50b250f59e94459

**Comment by hulpke** [comment]
1) is already done.
I have just committed changes that I believe do 2,3,4.
