### ISSUE TITLE
Taking over BrowseTransitiveGroupsInfo

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#26]
This is a reminder about the solution agreed in  https://github.com/gap-system/gap/issues/1012

* removing `BrowseTransitiveGroupsInfo` from the Browse package (done)
* taking over this functionality from Browse and adjusting it to the new setup.

**Comment by fingolfin** [comment]
@hulpke you added a wontfix label, but left the issue open. Could you clarify what that means? Just that you won't work on this, or that you would reject any PR adding this functionality?

**Comment by hulpke** [comment]
I can close the issue if that makes it look cleaner.
If smeone wants to propose a PR that adds (only) browse functionality I won't reject it, but I think it is not worth anyone's time to implement it (just because there used to be a browse package in the past).
