### ISSUE TITLE
Setting up URL for this repository

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#27]
@hulpke, It would be convenient if you could set the homepage URL of this repository to http://www.math.colostate.edu/~hulpke/transgrp/ (which I hope will eventually get a proper webpage).

To do that, go to the front page of this repository. To the right of the description placeholder  "No description, website, or topics provided" there should be a button labelled "Edit", which when clicked also allows you to enter a description and specify a website.

**Comment by hulpke** [comment]
Done

**Comment by olexandr-konovalov** [comment]
@hulpke thanks. Actually, I've suggested to set a description as well (e.g. "GAP Transitive Groups Library"). It's convenient if such short description is on top of the repository page, and also it will be seen at https://github.com/hulpke?tab=repositories (you can do the same for other repositories of yours, too).
