### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#28]
The website for the package is specified as https://github.com/hulpke/transgrp and it only contains a list of files. It will be nice to establish a kind of a webpage similar to https://gap-packages.github.io/smallgrp/ - after all, this is a package **needed** to run GAP.

Also, I've noticed that the link from the `PackageInfo.g` to http://www.math.colostate.edu/~hulpke/transgrp/README.txt file is available, but the file is not visible in the directory listing at http://www.math.colostate.edu/~hulpke/transgrp/ - at least correcting this would be an improvement. The users visiting the page will understand that it is in development, but at least they will be able to open the README and find out which orders are provided, and which have to be downloaded separately etc.

**Comment by olexandr-konovalov** [comment]
@hulpke as a quick measure, could you possibly at least put a `README.txt` file there, please?

**Comment by hulpke** [comment]
@alex-konovalov 
I'll try to remember, but why on earth is that an issue (respectively: why do scripts test separately for the readme file)?

**Comment by hulpke** [comment]
There is now a README.txt file in the folder (i.e. http://www.math.colostate.edu/%7Ehulpke/transgrp/README.txt

but for some reason I have no time to investigate the web browser does not display it.

The reason for not having an index file over it is that it would have to be edited every time there is a new release.

**Comment by olexandr-konovalov** [comment]
@hulpke the issue is that your package, which is quite important (GAP will not run without it) does not even have a website. So at least a tiny bit user friendliness could be added by placing a README there as a surrogate.

If you are happy to give me write access, I can experiment with establishing a website on GitHub pages to look similar to https://gap-packages.github.io/smallgrp/ and updated using scripts from ReleaseTools. The optional download file will reside in http://www.math.colostate.edu/~hulpke/transgrp/ and there will be a link to it.
