### ISSUE TITLE
Add all transitive groups of degree at most 47

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#32]
The README file says that

https://github.com/hulpke/transgrp/blob/55a90d6f8f7c8f351805a33a88a7c20aa8786d71/README.txt#L5

but I have 

```
gap> Filtered([1..50], i->not TransitiveGroupsAvailable(i));
[ 1, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50 ]
```

- are there any data files missing?

**Comment by fingolfin** [comment]
The READM also says: "Not all degrees >30 are yet available."

**Comment by olexandr-konovalov** [comment]
@fingolfin I seen that. While the PDF manual says:
> The transitive groups library currently contains representatives for all transitive permutation groups of degree at most 47. Due to the total number, degree 32 needs to be downloaded separately, see section “Supplemental Download” below.

**Comment by hulpke** [comment]
Another reason for not having a README :-)

In the missing degrees I did not yet get to run the full file conversion.

**Comment by olexandr-konovalov** [comment]
Ah, ok - that was likely the plan to complete it before some milestone GAP release, but was delayed. Perhaps adjust the manual then?

**Comment by olexandr-konovalov** [comment]
I've noticed that the manual now says "The transitive groups library will contain representatives for all
transitive permutation groups of degree at most  47.  Not all degrees might be yet available in the current release." and updated the title of this issue accordingly.
