### ISSUE TITLE
Old version appeared on the website

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#35]
Same as in https://github.com/hulpke/matgrp/issues/11 happened here:
```
Package: TransGrp
  removed components: [ "TestFile" ]
  new components: [ "Autoload" ]
  changed components: [ "Version", "Date", "PackageName", "PackageDoc", 
  "TestFile", "ArchiveURL", "AbstractHTML" ]
  ERROR (TransGrp): the new version 1.0 in the new info file from
  http://www.math.colostate.edu/~hulpke/transgrp/PackageInfo.g
  is not larger than the old version 2.0.4
  This is not allowed, so the info file will not be changed
  PackageInfo.g is not accepted because of an error.
```
Perhaps the website was accidentally overwritten by backup copy?

Could this be an incentive to start to use ReleaseTools and GitHubPagesForGAP to establish a properly looking website, and a release process which efficiently uses available functionality to automate all steps?

**Comment by olexandr-konovalov** [comment]
@hulpke have you seen this issue? You fixed MatGrp but not TransGrp.

**Comment by hulpke** [comment]
@alex-konovalov 
Yes I have seen it (and its the same reason) but I don't always have time to reply next day on such issues.

**Comment by olexandr-konovalov** [comment]
Thanks - I was worried that it's overlooked, since the other one was fixed immediately.

**Comment by hulpke** [comment]
Should be resolved now,.

**Comment by olexandr-konovalov** [comment]
@hulpke thanks!
