### ISSUE TITLE
Credits for degree 47

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#41]
Chapter 1 says

"The list of transitive groups up to degree 11 was published in BM83, the list of degree 12 was published in Roy87, degree 14 and 15 were published in Butler93 and degrees 16--30 were published in Hulpke96 and HulpkeTG. Degree 32 was published in CanHolt32, and degrees 34-46 have been obtained by Derek Holt (but are unpublished). Groups of prime degree of course are primitive and were known long before.

The transitive groups library currently contains representatives for all transitive permutation groups of degree at most 47. Due to the total number, degree 32 needs to be downloaded separately, see section ``Supplemental Download'' below"

To whom is credit due for degree 47 then?

**Comment by hulpke** [comment]
Since 47 is prime, the sentence "Groups of prime degree of course are primitive and were known long before" applies, I have not tried to track down who gave the relevant information first.
