### ISSUE TITLE
Deliver data files in compressed forms

### ISSUE THREAD

**Issue by fingolfin** [hulpke/transgrp#44]
Right now `transgrp` is by far the largest package in terms of disk space utilization: about 300 MB over here, out of 1.3 GB for all packages together. 

By running `gzip -9 data/*.grp`, this goes down to ~60 MB.

Perhaps you could modify your package release script to take care of this, i.e., it could compress those files before wrapping them into a tarball?

(Alternatively, use ReleaseTools, which makes this trivial to achieve and is how tomlib, smallgrp, and a few others do it)

**Comment by hulpke** [comment]
Is it guaranteed that the gzipped files will run on all platforms without trouble?

**Comment by fingolfin** [comment]
Yes

**Comment by hulpke** [comment]
Thanks. Latest archive has this now.
