### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fingolfin** [hulpke/transgrp#7]
The current license is unfortunately incompatible with the GPL, and indeed very restrictive, as it allows no modifications at all.

It would be nice if a more generous and "standard" license could be chosen -- e.g. the GPL, and BSD/MIT style license, a Creative Commons variant, etc. Or, since this is arguably mostly a data library, perhaps the Artistic License 2.0. Or any number of others...

**Comment by hulpke** [comment]
Yes, it probably should go to the artistic license (which I did not know of before), though you can argue whether the mathematical information itself is copyrightable.

**Comment by fingolfin** [comment]
While mathematical knowledge can not be copyrighted, one can argue that certain expressions of it can be (which is why there can be copyrights on papers).

Anyway, the point of the license in the end is that people are assured that they are allowed to use the data in certain ways, and that the authors won't object to it.
Those who believe its legal (and also OK from a morale point of view) to use it no matter what the the authors say or want have no problem with our without the license, after all :-)

**Comment by hulpke** [comment]
I have changed the license
