### ISSUE TITLE
Adding test files

### ISSUE THREAD

**Issue by olexandr-konovalov** [hulpke/transgrp#9]
I suggest to add a `tst` directory with some tests. We need at least a quick (up to several minutes) test to make several calls to the functions defined in this package to check that it works. This may be specified in `PackageInfo.g` file to be used in automated testing.

There may be more extensive tests, for example, to check TransitiveIdentification for each group from the library.

**Comment by hulpke** [comment]
I do not think this package needs its own test file or dedicated automatic tests. The access to the groups is tested already extensively through the main GAP test files.
On the other hand any deeper conceptual tests -- checking the classification -- are far beyond what is feasible in a test file.

**Comment by olexandr-konovalov** [comment]
I think they are needed, and will be happy to make a pull request to provide some (Look e.g. what I plan to do for PrimGrp at https://github.com/gap-packages/primgrp). This is useful not only to check that the package itself works, but also that new changes in the core GAP or new packages do not break any packages. And if there are tests which specifically tests this library in the main GAP test suite, they may be eventually transferred to TransGrp package.

**Comment by fingolfin** [comment]
Indeed, I'd move the tests for transitive groups from the main repos to this package.

**Comment by olexandr-konovalov** [comment]
Working on this now - I hope we may get at least tests for transitive groups from the main repo moved to this package in time for GAP 4.10.

**Comment by olexandr-konovalov** [comment]
I've added a basic test in PR #33. Haven't discovered much in the `tst` directory in GAP, except one bugfix file. There is also a benchmark, but that one tests generation of the list of such groups and requires more time - maybe that could be added later, but I've decided to skip looking at it now.

**Comment by olexandr-konovalov** [comment]
Started in #33 and completed by @hulpke in 2c5c88f55020379441c0454ba6bfcf94427ab2a1. Could be more files in the future, but for now we may close this.
